### PR TITLE
Ba requirements blogpost

### PR DESCRIPTION
**Pull request by merit-juliesc**

### CODE REVIEW

**Review by merit-ddennis — APPROVED** [review]
Nice post, Julie!

**Review by merit-akliang — APPROVED** [review]
Looks good to me!!!

**Review by merit-schelcj — CHANGES_REQUESTED** [review]
Content looks good, discussed markdown linting with Julie and she is addressing.

**Review by merit-rluk — APPROVED** [review]
Looks good - thanks for writing this up, Julie!

**Review by merit-amystuyv — APPROVED** [review]
Looks great!

**Pull request merged**
